---
name: theos-build
description: Build a package with theos
inputs:
  extra_args:
    description: 'Extra arguments to pass to Theos/make'
    default: ''
    required: false

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/*.md'
    branches:
      - main

runs:
  using: "composite"
  steps:
    - run: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/L1ghtmann/theos/pr8/bin/install-theos)"
      shell: bash
    - run: |
        export THEOS=~/theos
        make clean package FINALPACKAGE=1 ${{ inputs.extra_args }}
      shell: bash
