---
name: theos-build
description: Build a package with theos
inputs:
  sdk:
    description: 'Additional theos/sdks SDK to install (e.g., iPhoneOS14.5)'
    default: ''
    required: false
  extra_args:
    description: 'Extra arguments to pass to Theos/make'
    default: ''
    required: false

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/*.md'
    branches:
      - main

runs:
  using: "composite"
  steps:
    - run: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        curl -LO https://raw.githubusercontent.com/L1ghtmann/theos/install-sdk/bin/install-sdk
        chmod +x install-sdk
        export THEOS=~/theos
        ./install-sdk ${{ inputs.sdk }}
      shell: bash
    - run: |
        export THEOS=~/theos
        make clean package ${{ inputs.extra_args }}
      shell: bash
